import { Coupon, Product } from "./types";

export const CATEGORIES = ["Lighting", "Ceramics", "Textiles", "Furniture", "Fragrance"] as const;

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "terra-lamp",
    title: "Terra Table Lamp",
    subtitle: "Hand-finished, terracotta glaze",
    description:
      "A lamp thrown from fired clay with a matte terracotta glaze. Warm, diffused light through a linen shade. Every piece varies slightly in tone — this is handwork, not mass production.",
    price: 98,
    compareAtPrice: 116,
    currency: "USD",
    category: "Lighting",
    tags: ["new", "handmade"],
    status: "in_stock",
    stock: 14,
    images: ["/products/lamp-1.svg", "/products/lamp-2.svg"],
    accent: "#C1531B",
    size: "lg",
    variants: [{ label: "Shade colour", options: ["Milk", "Charcoal", "Ochre"] }],
  },
  {
    id: "p2",
    slug: "olive-vase-set",
    title: "Olive Vase Set",
    subtitle: "3 forms, one story",
    description:
      "A trio of ceramic vases at different heights for dried florals or branch arrangements. Sandy texture, raw-edged rims.",
    price: 68,
    currency: "USD",
    category: "Ceramics",
    tags: ["bestseller"],
    status: "low_stock",
    stock: 3,
    images: ["/products/vase-1.svg"],
    accent: "#5B6B4A",
    size: "md",
  },
  {
    id: "p3",
    slug: "linen-throw",
    title: "Umber Throw",
    subtitle: "100% linen, heavyweight weave",
    description:
      "A dense linen throw in an earthy palette. Softened by repeated washing, so it's already pleasant to the touch.",
    price: 78,
    currency: "USD",
    category: "Textiles",
    tags: [],
    status: "in_stock",
    stock: 22,
    images: ["/products/throw-1.svg"],
    accent: "#8A5A3B",
    size: "sm",
    variants: [{ label: "Size", options: ["130×170", "170×210"] }],
  },
  {
    id: "p4",
    slug: "amber-candle-trio",
    title: "Amber Candle Trio",
    subtitle: "Cedar, sandalwood, tobacco leaf",
    description:
      "Three soy candles in matte glass vessels. Burns up to 40 hours each. No paraffin, no synthetic dyes.",
    price: 40,
    currency: "USD",
    category: "Fragrance",
    tags: ["gift"],
    status: "in_stock",
    stock: 40,
    images: ["/products/candle-1.svg"],
    accent: "#E8B44A",
    size: "sm",
  },
  {
    id: "p5",
    slug: "oak-side-table",
    title: "Oak Side Table",
    subtitle: "Solid oak, waxed finish",
    description:
      "A compact side table cut from solid oak. Rounded edges, waxed finish that lets the grain show through.",
    price: 170,
    currency: "USD",
    category: "Furniture",
    tags: ["premium"],
    status: "preorder",
    stock: 0,
    images: ["/products/table-1.svg"],
    accent: "#4A3A2C",
    size: "lg",
  },
  {
    id: "p6",
    slug: "clay-mug-pair",
    title: "Duna Mug Pair",
    subtitle: "For coffee, tea, and long mornings",
    description: "Two 250ml ceramic mugs with thick walls that hold heat for a long time.",
    price: 29,
    currency: "USD",
    category: "Ceramics",
    tags: [],
    status: "sold_out",
    stock: 0,
    images: ["/products/mug-1.svg"],
    accent: "#C1531B",
    size: "sm",
  },
  {
    id: "p7",
    slug: "wool-cushion",
    title: "Merino Cushion",
    subtitle: "Merino wool fill, removable cover",
    description: "A soft accent cushion with a wool fill and a cover on a hidden zipper.",
    price: 36,
    currency: "USD",
    category: "Textiles",
    tags: ["new"],
    status: "in_stock",
    stock: 17,
    images: ["/products/cushion-1.svg"],
    accent: "#5B6B4A",
    size: "md",
    variants: [{ label: "Colour", options: ["Ochre", "Clay", "Moss"] }],
  },
  {
    id: "p8",
    slug: "brass-mirror",
    title: "Halo Mirror",
    subtitle: "Hand-bent brass frame",
    description: "A round mirror in a slim brass frame that develops a noble patina over time.",
    price: 128,
    currency: "USD",
    category: "Furniture",
    tags: ["bestseller"],
    status: "in_stock",
    stock: 6,
    images: ["/products/mirror-1.svg"],
    accent: "#B08A3E",
    size: "md",
  },
];

export const MOCK_COUPONS: Coupon[] = [
  { code: "TERRA10", kind: "percent", value: 10 },
  { code: "FIRST20", kind: "fixed", value: 20, minSubtotal: 60 },
];
