import { Coupon, Product } from "./types";

export const CATEGORIES = ["Освітлення", "Кераміка", "Текстиль", "Меблі", "Аромати"] as const;

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "terra-lamp",
    title: "Настільна лампа Terra",
    subtitle: "Ручна обробка, теракотова глазур",
    description:
      "Лампа з обпаленої глини з матовою теракотовою глазур'ю. Теплий розсіяний світловий потік, м'який плафон з бавовняного льону. Кожна одиниця відрізняється відтінком — це ручна робота, не масове виробництво.",
    price: 2450,
    compareAtPrice: 2900,
    currency: "UAH",
    category: "Освітлення",
    tags: ["новинка", "хендмейд"],
    status: "in_stock",
    stock: 14,
    images: ["/products/lamp-1.svg", "/products/lamp-2.svg"],
    accent: "#C1531B",
    size: "lg",
    variants: [{ label: "Колір плафону", options: ["Молочний", "Вугільний", "Вохра"] }],
  },
  {
    id: "p2",
    slug: "olive-vase-set",
    title: "Набір ваз Olive",
    subtitle: "3 форми, одна історія",
    description:
      "Тріо керамічних ваз різної висоти для композицій із сухоцвітів або гілок. Пісочна текстура, необроблений край вінця.",
    price: 1680,
    currency: "UAH",
    category: "Кераміка",
    tags: ["бестселер"],
    status: "low_stock",
    stock: 3,
    images: ["/products/vase-1.svg"],
    accent: "#5B6B4A",
    size: "md",
  },
  {
    id: "p3",
    slug: "linen-throw",
    title: "Плед Umber",
    subtitle: "100% лляна тканина, важка фактура",
    description:
      "Щільний лляний плед у землистій гамі. Пом'якшений багаторазовим пранням, тому одразу приємний на дотик.",
    price: 1920,
    currency: "UAH",
    category: "Текстиль",
    tags: [],
    status: "in_stock",
    stock: 22,
    images: ["/products/throw-1.svg"],
    accent: "#8A5A3B",
    size: "sm",
    variants: [{ label: "Розмір", options: ["130×170", "170×210"] }],
  },
  {
    id: "p4",
    slug: "amber-candle-trio",
    title: "Свічки Amber Trio",
    subtitle: "Кедр, сандал, тютюновий лист",
    description:
      "Три соєві свічки в матових скляних склянках. Час горіння — до 40 годин кожна. Без парафіну та синтетичних барвників.",
    price: 980,
    currency: "UAH",
    category: "Аромати",
    tags: ["подарунок"],
    status: "in_stock",
    stock: 40,
    images: ["/products/candle-1.svg"],
    accent: "#E8B44A",
    size: "sm",
  },
  {
    id: "p5",
    slug: "oak-side-table",
    title: "Приставний столик Oak",
    subtitle: "Масив дуба, воскова обробка",
    description:
      "Компактний столик із суцільного дубового масиву. Округлі кути, воскове покриття, що підкреслює текстуру дерева.",
    price: 4200,
    currency: "UAH",
    category: "Меблі",
    tags: ["преміум"],
    status: "preorder",
    stock: 0,
    images: ["/products/table-1.svg"],
    accent: "#4A3A2C",
    size: "lg",
  },
  {
    id: "p6",
    slug: "clay-mug-pair",
    title: "Пара чашок Duna",
    subtitle: "Для кави, чаю та довгих ранків",
    description: "Дві керамічні чашки об'ємом 250 мл із товстими стінками, що довго тримають тепло.",
    price: 720,
    currency: "UAH",
    category: "Кераміка",
    tags: [],
    status: "sold_out",
    stock: 0,
    images: ["/products/mug-1.svg"],
    accent: "#C1531B",
    size: "sm",
  },
  {
    id: "p7",
    slug: "wool-cushion",
    title: "Подушка Merino",
    subtitle: "Вовна мериноса, знімний чохол",
    description: "М'яка декоративна подушка з вовняним наповнювачем і чохлом на прихованій блискавці.",
    price: 890,
    currency: "UAH",
    category: "Текстиль",
    tags: ["новинка"],
    status: "in_stock",
    stock: 17,
    images: ["/products/cushion-1.svg"],
    accent: "#5B6B4A",
    size: "md",
    variants: [{ label: "Колір", options: ["Вохра", "Глина", "Мох"] }],
  },
  {
    id: "p8",
    slug: "brass-mirror",
    title: "Дзеркало Halo",
    subtitle: "Латунна рама ручної гнучки",
    description: "Кругле дзеркало в тонкій латунній рамі, що з часом набуває шляхетної патини.",
    price: 3150,
    currency: "UAH",
    category: "Меблі",
    tags: ["бестселер"],
    status: "in_stock",
    stock: 6,
    images: ["/products/mirror-1.svg"],
    accent: "#B08A3E",
    size: "md",
  },
];

export const MOCK_COUPONS: Coupon[] = [
  { code: "TERRA10", kind: "percent", value: 10 },
  { code: "FIRST200", kind: "fixed", value: 200, minSubtotal: 1500 },
];
