-- Seeds the same 8 demo products used in src/lib/mock-data.ts so the storefront
-- isn't empty right after connecting Supabase. Run after schema.sql.

insert into products (id, slug, title, subtitle, description, price, compare_at_price, currency, category, tags, status, stock, images, accent, size, variants) values
('p1', 'terra-lamp', 'Terra Table Lamp', 'Hand-finished, terracotta glaze', 'A lamp thrown from fired clay with a matte terracotta glaze. Warm, diffused light through a linen shade. Every piece varies slightly in tone — this is handwork, not mass production.', 98, 116, 'USD', 'Lighting', array['new','handmade'], 'in_stock', 14, array['/products/lamp-1.svg','/products/lamp-2.svg'], '#C1531B', 'lg', '[{"label":"Shade colour","options":["Milk","Charcoal","Ochre"]}]'::jsonb),
('p2', 'olive-vase-set', 'Olive Vase Set', '3 forms, one story', 'A trio of ceramic vases at different heights for dried florals or branch arrangements. Sandy texture, raw-edged rims.', 68, null, 'USD', 'Ceramics', array['bestseller'], 'low_stock', 3, array['/products/vase-1.svg'], '#5B6B4A', 'md', null),
('p3', 'linen-throw', 'Umber Throw', '100% linen, heavyweight weave', 'A dense linen throw in an earthy palette. Softened by repeated washing, so it''s already pleasant to the touch.', 78, null, 'USD', 'Textiles', array[]::text[], 'in_stock', 22, array['/products/throw-1.svg'], '#8A5A3B', 'sm', '[{"label":"Size","options":["130×170","170×210"]}]'::jsonb),
('p4', 'amber-candle-trio', 'Amber Candle Trio', 'Cedar, sandalwood, tobacco leaf', 'Three soy candles in matte glass vessels. Burns up to 40 hours each. No paraffin, no synthetic dyes.', 40, null, 'USD', 'Fragrance', array['gift'], 'in_stock', 40, array['/products/candle-1.svg'], '#E8B44A', 'sm', null),
('p5', 'oak-side-table', 'Oak Side Table', 'Solid oak, waxed finish', 'A compact side table cut from solid oak. Rounded edges, waxed finish that lets the grain show through.', 170, null, 'USD', 'Furniture', array['premium'], 'preorder', 0, array['/products/table-1.svg'], '#4A3A2C', 'lg', null),
('p6', 'clay-mug-pair', 'Duna Mug Pair', 'For coffee, tea, and long mornings', 'Two 250ml ceramic mugs with thick walls that hold heat for a long time.', 29, null, 'USD', 'Ceramics', array[]::text[], 'sold_out', 0, array['/products/mug-1.svg'], '#C1531B', 'sm', null),
('p7', 'wool-cushion', 'Merino Cushion', 'Merino wool fill, removable cover', 'A soft accent cushion with a wool fill and a cover on a hidden zipper.', 36, null, 'USD', 'Textiles', array['new'], 'in_stock', 17, array['/products/cushion-1.svg'], '#5B6B4A', 'md', '[{"label":"Colour","options":["Ochre","Clay","Moss"]}]'::jsonb),
('p8', 'brass-mirror', 'Halo Mirror', 'Hand-bent brass frame', 'A round mirror in a slim brass frame that develops a noble patina over time.', 128, null, 'USD', 'Furniture', array['bestseller'], 'in_stock', 6, array['/products/mirror-1.svg'], '#B08A3E', 'md', null)
on conflict (id) do nothing;
